package StepDefinition;

public class Locators {
	public static final String FEATURED_ITEMS = "/html/body/section[2]/div[1]/div/div[2]/div[1]/h2";
	public static final String ITEM_MODAL = "/html/body/section[2]/div[1]/div/div[2]/div[1]/div[2]";
	public static final String ADD_TO_CART = "/html/body/section[2]/div[1]/div/div[2]/div[1]/div[2]/div/div[1]/div[2]/div/a";
	public static final String CONTINUE_SHOPPING_BUTTON = "//*[@id=\"cartModal\"]/div/div/div[3]/button";
	public static final String SHOPPING_CART_PAGE = "//*[@id=\"header\"]/div/div/div/div[2]/div/ul/li[3]/a";
	public static final String SHOPPING_CART_PAGE_ASSERTION = "//*[@id=\"cart_items\"]/div/div[1]/ol/li[2]";
	public static final String PROCEED_TO_CHECKOUT_BUTTON = "//*[@id=\"do_action\"]/div[1]/div/div/a";
	public static final String REGISTER_LOGIN_BUTTON = "//*[@id=\"checkoutModal\"]/div/div/div[2]/p[2]/a/u";
	public static final String NAME_INPUT = "//*[@id=\"form\"]/div/div/div[3]/div/form/input[2]";
	public static final String EMAIL_INPUT = "//*[@id=\"form\"]/div/div/div[3]/div/form/input[3]";
	public static final String SIGNUP_BUTTON = "//*[@id=\"form\"]/div/div/div[3]/div/form/button";
	public static final String PASSWORD = "//*[@id=\"password\"]";
	public static final String FIRST_NAME = "//*[@id=\"first_name\"]";
	public static final String LAST_NAME = "//*[@id=\"last_name\"]";
	public static final String ADDRESS = "//*[@id=\"address1\"]";
	public static final String STATE = "//*[@id=\"state\"]";
	public static final String CITY = "//*[@id=\"city\"]";
	public static final String ZIPCODE = "//*[@id=\"zipcode\"]";
	public static final String PHONE_NUMBER = "//*[@id=\"mobile_number\"]";
	public static final String SUCCESSFUL_REGISTRATION_VERIFICATION = "//*[@id=\"form\"]/div/div/div/h2/b";
	public static final String CONTINUE_BUTTON = "//*[@id=\"form\"]/div/div/div/div/a";
	public static final String ACCOUNT_NAME = "//*[@id=\"header\"]/div/div/div/div[2]/div/ul/li[10]/a/b";
	public static final String DELIVERY_NAME = "//*[@id=\"address_delivery\"]/li[2]";
	public static final String DELIVERY_ADDRESS = "//*[@id=\"address_delivery\"]/li[4]";
	public static final String DELIVERY_CITY_STATE_ZIP = "//*[@id=\"address_delivery\"]/li[6]";
	public static final String DELIVERY_PHONE_NUMBER = "//*[@id=\"address_delivery\"]/li[8]";
	public static final String ORDER_DETAILS = "//*[@id=\"ordermsg\"]/textarea";
	public static final String PLACE_ORDER_BUTTON = "//*[@id=\"cart_items\"]/div/div[7]/a";
	public static final String CARD_OWNER_NAME = "//*[@id=\"payment-form\"]/div[1]/div/input";
	public static final String CARD_NUMBER = "//*[@id=\"payment-form\"]/div[2]/div/input";
	public static final String CVC = "//*[@id=\"payment-form\"]/div[3]/div[1]/input";
	public static final String CARD_EXPIRATION_MONTH = "//*[@id=\"payment-form\"]/div[3]/div[2]/input";
	public static final String CARD_EXPIRATION_YEAR = "//*[@id=\"payment-form\"]/div[3]/div[3]/input";
	public static final String PAY_AND_CONFIRM_ORDER_BUTTON = "//*[@id=\"submit\"]";
	public static final String ORDER_VERIFICATION = "//*[@id=\"form\"]/div/div/div/h2/b";
	public static final String DELETE_ACCOUNT_BUTTON = "//*[@id=\"form\"]/div/div/div/h2/b";
	public static final String DELETE_ACCOUNT_VERIFICATION = "//*[@id=\"form\"]/div/div/div/h2/b";
}
